name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Blueprint Checks
  blueprint-checks:
      uses: windsorcli/blueprint/.github/workflows/blueprint-checks.yaml@v0.0.1

  blueprint-checkov:
      uses: windsorcli/blueprint/.github/workflows/blueprint-checkov.yaml@v0.0.1
        
