name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  windsorblueprint_version: main

jobs:
  # Blueprint Checks
  blueprint-checks:
      uses: windsorcli/blueprint/.github/workflows/blueprint-checks.yaml@main

  blueprint-checkov:
      uses: windsorcli/blueprint/.github/workflows/blueprint-checkov.yaml@main
        
